#!/bin/bash

draw_line() {
    local spaces=$1
    local count=$2
    local char=$3

    local s=0
    while [ $s -lt $spaces ]; do
        echo -n " "
        s=$((s + 1))
    done

    for sym in $(seq 1 $count); do
        echo -n "$char"
    done
    echo
}

validate_input() {
    if [ "$#" -ne 2 ]; then
        echo "Необхідно вказати висоту дерева та ширину снігу!" >&2
        exit 1
    fi

	if ! [[ "$1" =~ ^[0-9]+$ && "$2" =~ ^[0-9]+$ ]]; then
        echo "Висота та сніг мають бути числами!" >&2
        exit 2
    fi

    if [ "$1" -le 0 ] || [ "$2" -le 0 ]; then
        echo "Параметри мають бути більше нуля!" >&2
        exit 3
    fi

    if [ "$2" -lt 7 ] || [ "$1" -lt 8 ]; then
        echo "Неможливо побудувати ялинку!" >&2
        exit 4
    fi

    local delta=$(( $1 - $2 ))

    case "$delta" in
        0|1|2) ;;
        *) echo "Неможливо побудувати ялинку!" >&2; exit 5 ;;
    esac

    if [ $(( $2 % 2 )) -ne 0 ] && [ $(( $1 % 2 )) -ne 0 ]; then
        if [ "$delta" -eq 0 ]; then
            echo "Неможливо побудувати ялинку!" >&2
            exit 6
        fi
    fi

    if [ $(( $2 % 2 )) -eq 0 ] && [ $(( $1 % 2 )) -eq 0 ]; then
		if [ "$delta" -eq 2 ]; then
			echo "Неможливо побудувати ялинку!" >&2
			exit 7
		fi
	fi
}

H=$1
W=$2

validate_input "$H" "$W"

symbol="*"
symbol_width=$((W - 2))
triangle_part=$(((H - 2) / 2))

if [ $((W % 2)) -eq 0 ]; then
    W=$((W - 1))
fi

for num in $(seq 1 2 "$symbol_width"); do
    spc=$(( (W - num) / 2 ))
    draw_line "$spc" "$num" "$symbol"
    symbol=$([[ "$symbol" = "*" ]] && echo "#" || echo "*")
done

symbol=$([[ "$symbol" = "*" ]] && echo "#" || echo "*")

for ((n=3; n<=symbol_width; n+=2)); do
    spc=$(( (W - n) / 2 ))
    symbol=$([[ "$symbol" = "*" ]] && echo "#" || echo "*")
    draw_line $spc $n "$symbol"
done

for _ in 1 2; do
    side=$(( (W - 3) / 2 ))
    draw_line $side 3 "#"
done

snow=0
until [ $snow -ge $W ]; do
    echo -n "*"
    snow=$((snow + 1))
done
echo
